# Generated by Django 3.1.4 on 2020-12-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20201212_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='valo',
            name='tel',
            field=models.CharField(default='', max_length=70),
        ),
    ]
