# Generated by Django 3.1.4 on 2020-12-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_valo_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='valo',
            name='fieldname',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
