# Generated by Django 3.1.4 on 2020-12-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_valo_fieldname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valo',
            name='fieldname',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
