# Generated by Django 3.1.4 on 2020-12-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20201213_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valo',
            name='fieldname',
            field=models.ImageField(default='', upload_to='static/vimages'),
        ),
    ]
