# Generated by Django 3.1.4 on 2020-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20201213_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valo',
            name='fieldname',
        ),
        migrations.AddField(
            model_name='valo',
            name='doc',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
